server:
  port: 80
spring:
  application:
    name: azure-demo
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/azuredemo?useSSL=false&serverTimezone=UTC
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect